ssid: !secret wifi_ssid
password: !secret wifi_password
manual_ip:
  static_ip: ${static_ip}
  gateway: 192.168.2.1
  subnet: 255.255.255.0
  dns1: 192.168.2.4
  dns2: 1.1.1.1
ap:
  ssid: ${ap_ssid}
  password: !secret ap_fallback_key

power_save_mode: none
